main:
  components_repository: "https://github.com/CAMM961001/house-prices"
  project_name: house_prices_clean_code
  steps: all
assets:
  train_set: "assets/train.csv"
  test_set: "assets/test.csv"
  data_description: "assets/data_description.txt"
  feature_selector: "assets/feature_selector.csv"
  processed_train: "assets/processed_train.csv"
  pipe_log: "assets/pipe_log.txt"
eda:
  img_size_small: (8, 6)
  img_size_medium: (10, 8)
  img_size_large: (12, 10)