main:
  components_repository: "https://github.com/CAMM961001/house-prices"
  project_name: house_prices_clean_code
  steps: all
assets:
  train_set: "data/raw/train.csv"
  test_set: "data/raw/test.csv"
  data_description: "assets/data_description.txt"
  feature_selector: "assets/feature_selector.csv"
  processed_train: "assets/processed_train.csv"
  processed_test: "assets/processed_test.csv"
  pipe_log: "assets/job_status.log"
  predictions: "assets/predictions.csv"
eda:
  img_size_small: (8, 6)
  img_size_medium: (10, 8)
  img_size_large: (12, 10)
model:
  max_leafs: 250
  n_folds: 10